rm x* o_*
split -l 1 run.sh o_
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_aa
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ab
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ac
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ad
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ae
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_af
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ag
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ah
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ai
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_aj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ak
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_al
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_am
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_an
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ao
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ap
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_aq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ar
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_as
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_at
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_au
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_av
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_aw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ax
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ay
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_az
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ba
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bd
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_be
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bf
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bi
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bl
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bo
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_br
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bs
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bt
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bu
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_by
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_bz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ca
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cd
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ce
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cf
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ch
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ci
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ck
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cl
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_co
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cr
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cs
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ct
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cu
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cy
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_cz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_da
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_db
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dd
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_de
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_df
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_di
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dl
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_do
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dr
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ds
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dt
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_du
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dy
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_dz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ea
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_eb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ec
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ed
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ee
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ef
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_eg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_eh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ei
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ej
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ek
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_el
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_em
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_en
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_eo
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ep
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_eq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_er
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_es
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_et
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_eu
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ev
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ew
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ex
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ey
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ez
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fa
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fd
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fe
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ff
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fi
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fl
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fo
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fr
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fs
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ft
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fu
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fy
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_fz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ga
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gd
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ge
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gf
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gi
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gl
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_go
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gr
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gs
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gt
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gu
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gy
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_gz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ha
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hd
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_he
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hf
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hi
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hl
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ho
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hr
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hs
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ht
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hu
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hy
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_hz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ia
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ib
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ic
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_id
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ie
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_if
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ig
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ih
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ii
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ij
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ik
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_il
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_im
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_in
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_io
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ip
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_iq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ir
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_is
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_it
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_iu
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_iv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_iw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ix
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_iy
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_iz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ja
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jd
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_je
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jf
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ji
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jl
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jo
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jr
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_js
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jt
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ju
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jy
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_jz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ka
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kd
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ke
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kf
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ki
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kl
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_km
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ko
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kr
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ks
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kt
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ku
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ky
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_kz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_la
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ld
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_le
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lf
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_li
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ll
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ln
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lo
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lr
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ls
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lt
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lu
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lv
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lw
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lx
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ly
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_lz
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ma
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mb
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mc
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_md
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_me
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mf
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mg
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mh
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mi
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mj
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mk
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_ml
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mm
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mn
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mo
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mp
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mq
qsub -cwd -l vf=0.2G, -l p=1 -q bc.q -P CATbhlR o_mr
